spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:file:./db/filmorate;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password

logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc: WARN