DROP ALL OBJECTS DELETE FILES;

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id int2 PRIMARY KEY AUTO_INCREMENT,
    name   varchar(80)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id int2 PRIMARY KEY AUTO_INCREMENT,
    name     varchar(20)
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_id       int2 REFERENCES mpa (mpa_id),
    name         varchar(250),
    description  varchar(200),
    release_date date,
    duration     int2 CHECK (duration >= 0)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    genre_id int2 REFERENCES genres (genre_id) ON DELETE CASCADE,
    film_id  int REFERENCES films (film_id) ON DELETE CASCADE,
    PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  int PRIMARY KEY AUTO_INCREMENT,
    login    varchar(20) UNIQUE  NOT NULL,
    name     varchar(50),
    email    varchar(320) UNIQUE NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS friendships
(
    from_user int REFERENCES users (user_id) ON DELETE CASCADE,
    to_user   int REFERENCES users (user_id) ON DELETE CASCADE,
    accepted  boolean DEFAULT false,
    PRIMARY KEY (from_user, to_user)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id int REFERENCES films (film_id) ON DELETE CASCADE,
    user_id int REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);